name: flexsell
description: A Flutter Point of Sale application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.0
  provider: ^6.1.0
  pdf: ^3.11.0
  printing: ^5.14.0
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
